# Safe: pull_request_target with adequate mitigations (permissions restriction)
# This should NOT trigger any dangerous-triggers rule
name: Dangerous Triggers Safe Example

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building PR with restricted permissions"
