# Safe workflow demonstrating proper use of secrets with network commands
# These patterns should NOT be flagged by the secret-exfiltration rule
# because they represent legitimate use cases

name: Secret Exfiltration Examples (Safe)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  github-api:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # GOOD: curl to GitHub API (trusted destination)
      - name: create release via GitHub API
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "v1.0.0"}'

      # GOOD: gh CLI (legitimate tool)
      - name: create issue with gh
        run: |
          gh issue create --title "Test" --body "Test issue"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package-publishing:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # GOOD: npm publish (legitimate publishing)
      - name: publish to npm
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # GOOD: docker login/push (legitimate CI/CD)
      - name: docker login
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      # GOOD: twine upload for Python packages
      - name: upload to PyPI
        run: |
          twine upload dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      # GOOD: gem push for Ruby packages
      - name: publish Ruby gem
        run: |
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      # GOOD: cargo publish for Rust crates
      - name: publish to crates.io
        run: |
          cargo publish --token ${{ secrets.CARGO_TOKEN }}

  cloud-authentication:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # GOOD: AWS CLI configuration
      - name: configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # GOOD: gcloud authentication
      - name: authenticate gcloud
        run: |
          gcloud auth activate-service-account --key-file=key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}

      # GOOD: Azure CLI login
      - name: azure login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # GOOD: kubectl config
      - name: configure kubectl
        run: |
          kubectl config set-credentials user --token=${{ secrets.K8S_TOKEN }}

  monitoring-services:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # GOOD: codecov upload
      - name: upload coverage to codecov
        run: |
          codecov -t ${{ secrets.CODECOV_TOKEN }}

      # GOOD: curl to Slack webhook (legitimate notification)
      - name: notify slack
        run: |
          curl -X POST https://hooks.slack.com/services/xxx/yyy/zzz \
            -H "Content-Type: application/json" \
            -d '{"text": "Build completed!"}'

      # GOOD: curl to codecov.io
      - name: upload to codecov via curl
        run: |
          curl -Os https://codecov.io/uploader/v0.3.0/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}

  infrastructure-tools:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # GOOD: terraform login
      - name: terraform cloud login
        run: |
          terraform login app.terraform.io
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      # GOOD: vault authentication
      - name: vault login
        run: |
          vault login -method=token token=${{ secrets.VAULT_TOKEN }}

  git-operations:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # GOOD: git push with token
      - name: git push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main

      # GOOD: git clone private repo
      - name: clone private repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/owner/private-repo

  no-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # GOOD: curl without secrets
      - name: fetch public data
        run: |
          curl -X GET https://api.example.com/public/status

      # GOOD: wget without secrets
      - name: download file
        run: |
          wget https://example.com/file.tar.gz

      # GOOD: dig for DNS lookup (no secrets)
      - name: dns lookup
        run: |
          dig example.com
