name: Test Edge Cases for secrets-in-artifacts

on: push

jobs:
  # Test 1: v1 (should detect - old version)
  test-v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload with v1
        uses: actions/upload-artifact@v1
        with:
          name: test-v1
          path: dist/

  # Test 2: Short SHA (should NOT detect - version unknown)
  test-short-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload with short SHA
        uses: actions/upload-artifact@6b208ae
        with:
          name: test-short-sha
          path: dist/

  # Test 3: Full SHA (should NOT detect - version unknown)
  test-full-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload with full SHA
        uses: actions/upload-artifact@6b208ae046db98c579e8a3aa621ab581ff575935
        with:
          name: test-full-sha
          path: dist/

  # Test 4: Branch name main (should NOT detect - version unknown)
  test-branch-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload with branch main
        uses: actions/upload-artifact@main
        with:
          name: test-main
          path: dist/

  # Test 5: .docker/config.json (should NOT detect - pattern missing)
  test-docker-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload docker config
        uses: actions/upload-artifact@v4
        with:
          name: test-docker
          path: .docker/config.json

  # Test 6: .terraform directory (should NOT detect - pattern missing)
  test-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload terraform
        uses: actions/upload-artifact@v4
        with:
          name: test-terraform
          path: .terraform/

  # Test 7: .env file (SHOULD detect - sensitive file)
  test-env-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload env file
        uses: actions/upload-artifact@v4
        with:
          name: test-env
          path: .env

  # Test 8: v3 without include-hidden-files (SHOULD detect)
  test-v3-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload with v3
        uses: actions/upload-artifact@v3
        with:
          name: test-v3
          path: dist/

  # Test 9: v4 with path: . (should NOT detect - v4 safe by default)
  test-v4-dot-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload entire repo with v4
        uses: actions/upload-artifact@v4
        with:
          name: test-v4-dot
          path: .

  # Test 10: v4 with include-hidden-files: true and path: . (SHOULD detect)
  test-v4-hidden-true:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload with hidden files enabled
        uses: actions/upload-artifact@v4
        with:
          name: test-v4-hidden
          path: .
          include-hidden-files: true
