name: Test secrets inherit

on: push

jobs:
  # BAD: secrets: inherit should be detected
  call-workflow-inherit:
    uses: ./.github/workflows/called.yml
    secrets: inherit

  # GOOD: explicit secrets are specified
  call-workflow-explicit:
    uses: ./.github/workflows/called.yml
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  # BAD: external workflow with inherit
  call-external-inherit:
    uses: owner/repo/.github/workflows/workflow.yml@v1
    secrets: inherit

  # GOOD: no secrets needed
  call-workflow-no-secrets:
    uses: ./.github/workflows/no-secrets.yml
