# GHSA-mrrh-fwg8-r2c3: tj-actions/changed-files supply chain attack
# Advisory: https://github.com/advisories/GHSA-mrrh-fwg8-r2c3
# Affected Action: tj-actions/changed-files
# Vulnerability Type: Supply Chain Attack - Secrets Dumping
# Expected Detection Rule: KnownVulnerableActionsRule

name: GHSA-mrrh-fwg8-r2c3 Vulnerable Pattern
on:
  pull_request:

jobs:
  vulnerable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Vulnerable: v45 was compromised and dumped secrets from memory
      # The action uploaded secrets to attacker-controlled server
      - uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.go
            **/*.ts

      - name: Process changed files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
