# GHSA-mcph-m25j-8j63: Command injection via filenames with special characters in tj-actions/changed-files
# Advisory: https://github.com/advisories/GHSA-mcph-m25j-8j63
# Safe Pattern: Use environment variables and proper array handling

name: Safe - Command Injection via Changed Files

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  changed-files-safe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files (safe pattern)
        id: changed-files
        run: |
          ALL_CHANGED_FILES="src/main.go src/test.go"
          echo "all_changed_files=$ALL_CHANGED_FILES" >> "$GITHUB_OUTPUT"

      - name: Process files (safe)
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Safe: Use environment variable with proper quoting
          while IFS= read -r file; do
            echo "Linting: $file"
          done <<< "$ALL_CHANGED_FILES"

      - name: Count changed files (safe)
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Safe: Use environment variable
          FILE_COUNT=$(echo "$ALL_CHANGED_FILES" | wc -w)
          echo "Changed $FILE_COUNT files"
